### ISSUE TITLE
Create XML to allow Insulin to be harvested from Pigs

### ISSUE THREAD

**Issue by zhrocks11** [Rimworld-Modding-Collaborative/MedicalOverhaulProject#37]

**Comment by Abaddon16** [comment]
Rename to Insulin. Need to modify MOP_WorkGivers.xml && create C# WorkGiver file to make it work. Pigs are making "milk" (insulin) already, just can't extract it.

**Comment by Abaddon16** [comment]
Required multi-file approach. Some files are now agnostic, some are fluid specific. 

All files that I needed
Drugs/MOP_Insulin.xml
JobDefs/MOP_Jobs-ExtractRawInsulin.xml
WorkGiverDefs/MOP_WorkGivers.xml (just added extractRawInsulin WorkGiver at the end)
Patches/MakePigsProduceInsulin.xml
ExtractRawFluids/CompProperties_RawFluidExtractable.cs
ExtractRawFluids/CompRawFluidExtractable.cs
ExtractRawFluids/JobDriver_ExtractRawFluid.cs
ExtractRawFluids/WorkGiver_ExtractRawInsulin.cs


Fluid Specific (need a new set for each fluid, probably)
 - Drugs/MOP_Insulin.xml
 - JobDefs/MOP_Jobs-ExtractRawInsulin.xml
 - WorkGiverDefs/MOP_WorkGivers.xml
 - Patches/MakePigsProduceInsulin.xml 
 - ExtractRawFluids/WorkGiver_ExtractRawInsulin.cs

Fluid Agnostic (should be applicable across multiple fluids)
 - ExtractRawFluids/CompProperties_RawFluidExtractable.cs
 - ExtractRawFluids/CompRawFluidExtractable.cs
 - ExtractRawFluids/JobDriver_ExtractRawFluid.cs

**Comment by Abaddon16** [comment]
Initial efforts completed. Future bugs, alterations, will open their own Issue
