### ISSUE TITLE
Create Poppy Juice Texture

### ISSUE THREAD

**Issue by zhrocks11** [Rimworld-Modding-Collaborative/MedicalOverhaulProject#5]
Create a texture for the harvested poppy juice, This will be the harvested form after it goes through the workbench, Poppies excrete a while liquid when cut and that's how its harvested. See image below for reference. 

https://i.pinimg.com/originals/8a/41/c4/8a41c403af01dfc616330ca6932562d0.jpg

Leaving this up to your artistic freedom, We need a texture for a contained form of that, You could make it into jars, Blows, Cups, its totally up to you. we just need a texture for a contained form.

**Comment by Axinex** [comment]
Initial textures complete for small, medium and large quantity stacks.
https://puu.sh/FaGSC/53bd5f1695.png
https://puu.sh/FaGSU/ee69f7515a.png
https://puu.sh/FaGT0/78f437775f.png

**Comment by Axinex** [comment]
Third revision textures complete for small, medium, and large quantity stacks.
