### ISSUE TITLE
Create Custom workbench Texture

### ISSUE THREAD

**Issue by zhrocks11** [Rimworld-Modding-Collaborative/MedicalOverhaulProject#6]
Create a custom workbench texture, Ideally should look like an upgraded version of the current drug lab. Something high tech looking where pawns will take things like the poppies and extract the juice from them and synthesize it into medicine

**Comment by Axinex** [comment]
Initial texture complete.
Preview: https://puu.sh/FaFvV/e66e7e58d9.png
