### ISSUE TITLE
Create XML for Poppy Plant

### ISSUE THREAD

**Issue by zhrocks11** [Rimworld-Modding-Collaborative/MedicalOverhaulProject#9]

**Comment by Abaddon16** [comment]
Created initial whack at the poppy plant XML. Specific data will be needed, along with play testing, to make the files realistic enough.

The file structure and naming convention used is based on the Core RimWorld files. I included 'MOP' where appropriate to denote the mod of the file, to reduce the risk of inter-mod issues (i.e.- increase compatibility)
